#!/usr/bin/env -S bun run
// scripts/emit-version-modules.ts
//
// Codegen for the per-version TypeScript wrappers that sit alongside
// each `generated/<version>/*.json` defs.
//
// For every version we track, we emit one file:
//
//   generated/<version>/index.ts      one module, all exports —
//                                     createParser / createTokenizer
//                                     pre-bound to this version's
//                                     dumps, plus a `parse(sql)` /
//                                     `tokenize(sql)` convenience
//                                     API, re-exported types, and the
//                                     raw defs objects.
//
// The reason this file exists at all (vs. hand-authored per-version
// modules) is that every version's wrapper is boilerplate save one
// version string.  Codegen keeps the set consistent and makes "what
// does the version wrapper look like?" a one-place question.
//
// There's also one cross-version file:
//
//   generated/current.ts              re-exports the version named
//                                     by vendor/manifest.json's
//                                     `current` field.  This is what
//                                     a bare `import '<package-name>'`
//                                     resolves to by default (where
//                                     <package-name> is taken from
//                                     package.json — see PACKAGE_NAME).
//
// Usage:
//   bun scripts/emit-version-modules.ts <version>
//       Emit just one version's index.ts.  Does NOT touch current.ts.
//
//   bun scripts/emit-version-modules.ts --current
//       Regenerate current.ts from the manifest.  Does NOT touch any
//       per-version index.ts.
//
//   bun scripts/emit-version-modules.ts --all
//       Regenerate index.ts for every version in the manifest AND
//       current.ts.  Used by the Makefile as a belt-and-suspenders
//       target for full rebuilds.
//
// The Makefile invokes these per-version; scripts/vendor.ts invokes
// `--current` after onboarding a new version.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { dirname, join, resolve } from "node:path"

import { PACKAGE_NAME, rootPath, rootRelativePath } from "./package-info.ts"

const MANIFEST = rootPath("vendor", "manifest.json")
const TEMPLATE = rootPath("generated", "template", "index.ts")
const TEMPLATE_CONTENT = readFileSync(TEMPLATE, "utf8")
const SELF = rootRelativePath(__filename)

interface Manifest {
  manifestVersion: number
  current: string
  versions: Record<string, unknown>
}

function readManifest(): Manifest {
  return JSON.parse(readFileSync(MANIFEST, "utf8"))
}

// ---------------------------------------------------------------------------
// Templates.
// ---------------------------------------------------------------------------

/**
 * One module per version.  Imports the prod (slim) dumps and wraps the
 * src/ API so consumers don't have to plumb dumps through by hand.
 *
 * Consumers who want the full (dev) dumps — e.g. for debugging or
 * inspecting rule actionC source — can import them directly via a
 * subpath like `<package-name>/<version>/parser.dev.json` (the
 * package name is baked into the generated comment from package.json
 * via the PACKAGE_NAME constant).
 */
function indexModule(version: string): string {
  return TEMPLATE_CONTENT.replace("__VERSION__", version).replace("__GENERATOR__", SELF)
}

/**
 * Cross-version re-export shim.  A bare `import '<package-name>'`
 * resolves to this file (see package.json's `main`), which re-exports
 * whatever version is marked current in the manifest.  Regenerated
 * whenever the vendor flow lands a new version.
 */
function currentModule(current: string): string {
  return `// AUTO-GENERATED by ${SELF} — do not edit.
//
// Re-export shim for the version the manifest currently names as
// \`current\`.  The vendor flow regenerates this whenever a new
// version is onboarded.  Consumers who want to pin a specific
// version explicitly should import from the versioned subpath
// instead: \`${PACKAGE_NAME}/sqlite-<version>\`.

export * from './${current}/index.ts';
`
}

// ---------------------------------------------------------------------------
// Writers.
// ---------------------------------------------------------------------------

function emitVersion(version: string): void {
  const outDir = rootPath("generated", version)
  mkdirSync(outDir, { recursive: true })
  const outPath = join(outDir, "index.ts")
  writeFileSync(outPath, indexModule(version))
  console.log(`wrote ${outPath}`)
}

function emitCurrent(current: string): void {
  const outPath = rootPath("generated", "current.ts")
  writeFileSync(outPath, currentModule(current))
  console.log(`wrote ${outPath} (→ ${current})`)
}

// ---------------------------------------------------------------------------
// CLI.
// ---------------------------------------------------------------------------

function main(): void {
  const [, , ...argv] = process.argv

  if (argv.includes("--help") || argv.includes("-h")) {
    console.log(
      "usage: bun scripts/emit-version-modules.ts <version>\n" +
        "       bun scripts/emit-version-modules.ts --current\n" +
        "       bun scripts/emit-version-modules.ts --all",
    )
    process.exit(0)
  }

  const manifest = readManifest()

  if (argv.includes("--all")) {
    for (const v of Object.keys(manifest.versions)) emitVersion(v)
    emitCurrent(manifest.current)
    return
  }

  if (argv.includes("--current")) {
    emitCurrent(manifest.current)
    return
  }

  const positional = argv.filter((a) => !a.startsWith("--"))
  if (positional.length !== 1) {
    console.error("usage: bun scripts/emit-version-modules.ts {<version>|--current|--all}")
    process.exit(2)
  }
  emitVersion(positional[0]!)
}

main()
