#!/usr/bin/env bun
// Emit a TypeScript module that embeds keywords.prod.json as a typed
// const, so the runtime version index imports `./keywords.ts` instead
// of relying on JSON module imports.  Keeping the data in a .ts file
// means the shipped `dist/` tree is pure JavaScript — no sibling JSON
// to copy, no bundler JSON import-assertion handling.
//
// Usage:
//   bun scripts/emit-keywords-module.ts <keywords.prod.json>  > <out.ts>

import { readFileSync } from "node:fs"

import { rootRelativePath, runScript } from "./utils.ts"

const USAGE = "usage: bun scripts/emit-keywords-module.ts <keywords.prod.json>  > <out.ts>"

await runScript(import.meta.main, { usage: USAGE }, ({ positionals }) => {
  const [inputPath] = positionals
  if (!inputPath) {
    console.error(USAGE)
    process.exit(2)
  }
  const data = JSON.parse(readFileSync(inputPath, "utf8"))
  const body = `// GENERATED by scripts/emit-keywords-module.ts — DO NOT EDIT.
// Source: ${rootRelativePath(inputPath)}

import type { KeywordDefs } from "../../src/tokenize.ts"

// \`as unknown as\` because KeywordDefs uses the branded KeywordMask
// number; plain JSON literals aren't directly assignable to it.
export const KEYWORDS_DEFS = ${JSON.stringify(data, undefined, 2)} as unknown as KeywordDefs
`
  process.stdout.write(body)
})
