#!/usr/bin/env -S bun run
// scripts/emit-version-modules.ts
//
// Codegen for the per-version TypeScript wrappers that sit alongside
// each `generated/<version>/*.json` defs.
//
// For every version we track, we emit one file:
//
//   generated/<version>/index.ts      one module, all exports —
//                                     createParser / createTokenizer
//                                     pre-bound to this version's
//                                     dumps, plus a `parse(sql)` /
//                                     `tokenize(sql)` convenience
//                                     API, re-exported types, and the
//                                     raw defs objects.
//
// The reason this file exists at all (vs. hand-authored per-version
// modules) is that every version's wrapper is boilerplate save one
// version string.  Codegen keeps the set consistent and makes "what
// does the version wrapper look like?" a one-place question.
//
// There's also one cross-version file:
//
//   generated/current.ts              re-exports the version named
//                                     by vendor/manifest.json's
//                                     `current` field.  This is what
//                                     a bare `import '<package-name>'`
//                                     resolves to by default (where
//                                     <package-name> is taken from
//                                     package.json — see PACKAGE_NAME).
//
// Usage:
//   bun scripts/emit-version-modules.ts version \
//       <version-string> <template> <index-out>
//       Emit one version's index.ts from the given template.
//
//   bun scripts/emit-version-modules.ts current <manifest-json> <out>
//       Regenerate the cross-version re-export shim from the manifest's
//       `current` field.
//
// The Makefile invokes these per-version; scripts/vendor.ts invokes
// `current` after onboarding a new version.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs"
import { dirname } from "node:path"

import { PACKAGE_NAME, rootRelativePath } from "./package-info.ts"

const SELF = rootRelativePath(__filename)

interface Manifest {
  manifestVersion: number
  current: string
  versions: Record<string, unknown>
}

// ---------------------------------------------------------------------------
// Templates.
// ---------------------------------------------------------------------------

/**
 * One module per version.  Reads the per-version template (which
 * references the generated `./lemonpar2.ts` and shared `../../src/*`
 * modules) and substitutes in the concrete version string.
 */
function indexModule(version: string, templateContent: string): string {
  return templateContent.replaceAll("__VERSION__", version).replaceAll("__GENERATOR__", SELF)
}

/**
 * Cross-version re-export shim.  A bare `import '<package-name>'`
 * resolves to this file (see package.json's `main`), which re-exports
 * whatever version is marked current in the manifest.  Regenerated
 * whenever the vendor flow lands a new version.
 */
function currentModule(current: string): string {
  return `// AUTO-GENERATED by ${SELF} — do not edit.
//
// Re-export shim for the version the manifest currently names as
// \`current\`.  The vendor flow regenerates this whenever a new
// version is onboarded.  Consumers who want to pin a specific
// version explicitly should import from the versioned subpath
// instead: \`${PACKAGE_NAME}/sqlite-<version>\`.

export * from './${current}/index.ts';
`
}

// ---------------------------------------------------------------------------
// Writers.
// ---------------------------------------------------------------------------

function writeFileMkdir(path: string, contents: string): void {
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, contents)
  console.log(`wrote ${path}`)
}

function emitVersion(args: {
  version: string
  templatePath: string
  indexOut: string
}): void {
  const templateContent = readFileSync(args.templatePath, "utf8")
  writeFileMkdir(args.indexOut, indexModule(args.version, templateContent))
}

function emitCurrent(manifestPath: string, outPath: string): void {
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as Manifest
  writeFileMkdir(outPath, currentModule(manifest.current))
  console.log(`  → ${manifest.current}`)
}

// ---------------------------------------------------------------------------
// CLI.
// ---------------------------------------------------------------------------

const USAGE =
  "usage: bun scripts/emit-version-modules.ts version <version-string> <template> <index-out>\n" +
  "       bun scripts/emit-version-modules.ts current <manifest-json> <out>"

function main(): void {
  const [, , mode, ...rest] = process.argv

  if (mode === "--help" || mode === "-h") {
    console.log(USAGE)
    process.exit(0)
  }

  if (mode === "version") {
    const [version, templatePath, indexOut] = rest
    if (!version || !templatePath || !indexOut) {
      console.error(USAGE)
      process.exit(2)
    }
    emitVersion({ version, templatePath, indexOut })
    return
  }

  if (mode === "current") {
    const [manifestPath, outPath] = rest
    if (!manifestPath || !outPath) {
      console.error(USAGE)
      process.exit(2)
    }
    emitCurrent(manifestPath, outPath)
    return
  }

  console.error(USAGE)
  process.exit(2)
}

main()
